### ISSUE TITLE
[Feature Request] Paste support

### ISSUE THREAD

**Issue by gfiorav** [christianfosli/wsl-copy#3]
## Context

It would be great if we could add the capability of pasting from the system clipboard too.

Thanks for this plugin, btw, I was about to go out and build my own!

**Comment by christianfosli** [comment]
Thanks.

Not really sure how to make that work.
I just `<Shift><Insert>` in insert mode to paste from the system clipboard (`:set paste` first makes it a bit better).

Edit:
I guess it's actually pretty easy, could add a function that sets "paste" mode, goes into insert mode, does `<shift><insert>`, then turns off "paste" mode. Would need to decide on a keyboard shortcut to use.

Edit2:
Eeeh, while `<shift><insert>` works fine in wsltty, which I'm using, it won't work in Powershell or CMD.exe. In those terminals a right-click is used to paste. That makes it a bit difficult..

**Comment by gfiorav** [comment]
Hey @christianfosli thanks for looking into this.

You're right, `<Shift><Insert>` is terminal app dependent. I've researched around, and it seems that Microsoft does not ship any standard paste solution. There's `paste.exe` but it's not guaranteed to be there. If it were, it would be very easy to do!

**Comment by christianfosli** [comment]
I'm gonna close this for now, as there doesn't seem to be a good way to do it that works anywhere, without installing external tools.

Thanks for the suggestion, though @gfiorav 😄
