### ISSUE TITLE
[Proposal] Change default mapping to other than 'w' prefix

### ISSUE THREAD

**Issue by gfiorav** [christianfosli/wsl-copy#4]
This plugin is great, but the fact that it uses a `w` mapping makes all other `w` commands (including advance word) wait for tails, which can be annoying.

As easy as it might be to remap this behavior (I've seen your README.md), would it make sense to change the prefix to something else?

`yw for example?

**Comment by christianfosli** [comment]
Good idea. Was thinking maybe it *may* be confusing to other users if the default mapping suddenly changed. But I don't think there are that many users, so I could go ahead.

The \` key is already used for jumping to a mark though, so that would cause a similar issue. Maybe Control-Y?

Edit: Control-Y scrolls one line up, so that's not a great Idea either

**Comment by gfiorav** [comment]
Hey, thanks for considering this!

I wish someone would develop an extension that would output all unbinded keys in one's setup... :)

How about an option to not bind this at all? I wouldn't see a problem having to type `:wsly` manually... The other option is to use a buffer for this, so you can do something like `y"+` to copy to clipboard (I believe that is the "clipboard" buffer by default, btw).

**Comment by christianfosli** [comment]
Yeah, using the default `"+y` or `"*y` would be awesome. I initially tried to use that as a mapping, but it doesn't work like that. Also these two buffers are not available for vim versions without clipboard support, such as the default Ubuntu vim.

I'll have a look at just using a command. Thanks for suggestions 😄

**Comment by gfiorav** [comment]
Hey, reading https://vi.stackexchange.com/questions/836/what-is-leader, it strikes me that we don't have to take away pre-existing bindings, we can use <Leader> (apparently that's what it was designed for).

**Comment by christianfosli** [comment]
Thanks, yea, I use `<Leader>` for a lot of my personal mappings. However, I read on the /r/vim subreddit that it shouldn't be used for plugins. See [here](https://www.reddit.com/r/vim/comments/87nosh/why_dont_people_like_leader_mappings/)

**Comment by christianfosli** [comment]
@gfiorav I have now removed default mapping, and added `:Wsly` command.
Note that the command, being a user defined command, had to start with a capital letter.

Thanks for suggestions 😄

**Comment by gfiorav** [comment]
Absolute hero! Thanks a lot!
